- theme/mkdocs/css/docs.css
This adds some basic styling for tables in the documentation. Styling is based on a mix of GitHub tables and tweaked a bit to match the documentation theme.
With this change inline-styles of existing tables can be removed and html-tables can be replaced with plain MarkDown tables in most cases.
Some examples;
Before:
After:
Plain MarkDown table:
> Add styling for tables

- Dockerfile
> Need to reset the theme so that the docker/docker docs metadata is rendered

- config.toml
For the 1.7 release Docker Trusted Registry is still Docker Hub Enterprise
> Dhe 1.0 support

- config.toml
* Currently, the docs.docker.com versions are broken as the css and javascript they expect to be located relative to root were removed with the old versions
- This is a temporary fix to the beta site to help users needing to see the old documents
> Temporarily redirecting to beta site

- config.toml
This is pretty self explanatory. Just fixing a minor typo in the table of contents.
> Fix TOC typo in section Administrate Docker

- Dockerfile
We can use subversion tools to retrieve the contents of the docs subdirectory from our repositories. This allows project repos to build the entire public docs from docs.docker.com.  
> Include subversion tools

- config.toml
Temporarily had the old docs pointed to beta while I fixed things.
All fixed up ready to correct.
> Correcting the links after the fix to the old docs

- config.toml
for now, I've put it under the DTR menu - and I'll add a referring topic under the `Command and API references` section.
I can do it the other way around too - needs discussion with @rajat-docker
> Add a DTR API submenu, and fix some whitespace

- Dockerfile
- supser-sed allows me to use Perl regex and thererfore lookahead in the build scripts
> Add ssed into the base system

- config.toml
As discussed in https://github.com/docker/docs-base/pull/131#discussion_r37223038
According to Scott Johnston, VP of Product, "Public Hub" was never vetted nor
approved. It should be changed back to "Docker Hub".
I didn't change the identifier (`smh_pubhub`) because that would involve changes in other repositories, but could be something we want at some point :)
> Rename "The Public Hub" to "Docker Hub"

- content/release-notes.md
This makes them more stable - in particular, we recently renamed CHANGES.md to CHANGELOG.md in Compose master, breaking the current link.
> Lock changelog links to release tags

- Dockerfile
- Makefile
- config.toml
- content/apidocs.md
- content/release-notes.md
- layouts/404.html
- layouts/apidocs/single.html
- layouts/partials/header.html
- validate.sh
for the Docker 1.9.0 RC's
This now uses http://github.com/docker/hugo to pull the hugo binary from.
> Hugo GitHub linking

- jenkins-validate.sh
damnit, i forget that `rm` can 'fail' - but it seems 'more' doesn't?
> Output junit files to console

- content/test.md
The documentation build is failing because of an issue in docs-base.  This fixes it
ping @SvenDowideit @thaJeztah
> Fixing break in documnetation biuld

- layouts/404.html
- static/css/custom.css
I've re-purposed this PR.
Fixes the style of any short pages (like the 404 page). Instead of having the footer in the middle of the page, it gets locked to the bottom of the page.
Compare: https://docs.docker.com/engine/userguide/networking/
vs: http://docs-stage.docker.com/engine/userguide/networking/
(assuming no one pushes a different branch to stage).
The footer is placed at the bottom, and doesn't crowd the text.
> Fix the footer position on short pages

- layouts/partials/compose-navbar.html
- layouts/partials/dtr-navbar.html
- layouts/partials/engine-navbar.html
- layouts/partials/hub-navbar.html
- layouts/partials/kitematic-navbar.html
- layouts/partials/machine-navbar.html
- layouts/partials/registry-navbar.html
- layouts/partials/swarm-navbar.html
- layouts/partials/tutorials-navbar.html
- themes/docker-docs/layouts/partials/navbar.html
@benbridge  This is the fix for the second level menus.  As styled, they weren't actually showing the arrow and the font was incorrect.  I also added a margin to the children via a `style` value on the child.  Maybe not the best way.
> Second level menus with children styling fix

- Dockerfile
This will not effect the v1.9 builds, as they use the `docs/base:hugo-github-linking` image
we will see some new errors reported, but... that's the idea :)
> Convert all log.Fatal* to log.Panic to generate a stack trace when hugo exits

- Dockerfile
- config.toml
> The github linking setting changed names when it was merged into hugo master

- config.toml
fixes https://github.com/docker/docs-base/issues/189
but depends on an updated version of our Hugo fork :smile:
> Don't convert double dashes to em-dash

- static/css/custom.css
This updates the styling of code-blocks and "notes" in the documentation
- Inline code is no longer wrapped
- Added back the left-hand border to "notes"
Not included in this PR, but a possible change to make, is to change the color for inline code examples / definitions. The border we currently use is (imo) a bit "busy" on the eye, so I created two variations below;
Finally, I think the font size of the code (-blocks) can be made *slightly* smaller, so that inline code more closely matches the size of the body-text, and we can fit a tiny bit more code in our example blocks.
With this change, it will look like this (note to self: `code: 0.95rem`, `pre > code: 0.8rem`):
> Update styling of code-blocks and notes

- config.toml
This fixes hash urls which contain ids: https://gohugo.io/overview/configuration/#configure-blackfriday-rendering
> Hugo changed the config key, now it's this.

- Dockerfile
> Update to markdownlint v0.9.5 - don't validate links in draft docs

- config.toml
do not merge until the other one is merged :)
> Remove the cloud api menu - it will be dealt with from its product repo

- config.toml
Reverts docker/docs-base#223
merge https://github.com/docker/cloud-docs/pull/48 first.
> removing cloud reference from the config.toml

- .gitignore
- Makefile
- README-DEV.md
@moxiegirl 
I wanted to add some helper targets to make the development setup on line command. After these additions you can run `make dev-all` from docs-base root and it will clone a copy of docker flickerbox-test under /devdeps/docker folder where it can further build/run the container under docker/docs. Whenever you have a style change under themes/docker-docs/static, you can run make-run and it will do the magic for you. There are also other sub-targets (dev-deps, dev-build and dev-build-static) which can be used individually.
I'm also planning to write a wiki page explaining these steps. Probably later today.
> Makefile targets for docs development

- jenkins-validate.sh
- validate.sh
@thaJeztah @moxiegirl this change is needed to allow us to run the checker on repos that have the docs somewhere else.
the jenkins job will get something like
`DOCSDIR=v1/docs jenkins-validate.sh`
> Allow the docs/ dir to be changed - some docs are in v1/docs/

- Dockerfile
- config.toml
replaces #226 
also need to set the new blackfriday sourceRelativeLinksProjectFolder setting that was added in this version of Hugo.
you need to remove the `--pull` from the `docs.docker.com` `Makefile` if you change the `Dockerfile` to use the image you've built locally from this branch.
> update to a new Hugo pre-release build with more fixes in it

- oss-projects/Dockerfile
- oss-projects/README.md
We've been using `svn checkout` for every writer and Jenkins job run of `make docs` to ensure that we're testing with the latest documentation from each repo.
This is now intermittently causing build failures due to the load we're putting on github, instead, I'll get Docker Hub to re-build a `docs/base:oss` image regularly, and then will change all the oss projects to use that image.
This increases the (small) probability of false problem reports by the checkers, or by writers, but in most cases should give everyone a faster docs experience.
> Add a base image file that can be used for testing

- static/css/custom.css
ligatures are a nice addition for regular text, but don't make a lot of sense for code samples.
this change disables ligatures for code blocks, to prevent (e.g.) 'fi' in '--filter' being replaced by a ligature.
screenshots below are made on iOS, which now supports "ligatures", so making this apparent 
before:
after:
> disable ligatures inside code blocks

- content/index.md
the "new navigation" has been around for a while now, so we can probably remove this.
> remove "new navigation" paragraph

- content/test/index.md
- content/test/menu.md
- layouts/menu/single.html
@sanscontext @londoncalling @sfsmithcha @joaofnfernandes 
This is the bare minimum `menu.md` that you can use to define a menu item. the `type="menu"` will mean that anyone navigating to that page will be sent to the index for that dir.
note that you can call the file anything else - if your IA needs an `menu.md` (or we could use something even more obscure like `zzz_menu.md` :)
> Add a menu layout type to redirect to the dir's index.html

- Dockerfile
> update linkcheck to not parse js/css and respect 404.html's baseUrl

- static/highlight/CHANGES.md
- static/highlight/README.md
- static/highlight/README.ru.md
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- themes/docker-2016/layouts/partials/footer.html
- themes/docker-2016/static/assets/js/anchorlinks.js
- themes/docker-2016/static/documentation.css
Adds clickable anchor links to headers (h1..h3) for
easier bookmarking or sharing links to specific
sections of the documentation.
fixes https://github.com/docker/docs-base/issues/98
Anchor-links are only visible on "hover";
> Add anchor-links

- data/advisories.toml
Use absolute URL to link to archive docs.
Signed-off-by: Charles Smith <charles.smith@docker.com>
> make links to archive absolute

- themes/docker-2016/static/documentation.css
change tables to be full-width at all times
for a more consistent layout. It's not perfect (yet),
because column-widths are still "auto", but overall
this gives a cleaner layout.
before and after below:
> change tables to be full-width

- themes/docker-2016/layouts/partials/footer.html
Whilst on subdomains *.docker.com the relative URL causes a 404 page to be displayed, changing to an absolute URL to the correct page
> Use absolute url for newsletter redirect

- themes/docker-2016/static/documentation.css
Signed-off-by: fish <fisher@docker.com>
@SvenDowideit @sanscontext added font weight to the accordion menu for legibility!
Boom!!!
> added font weight to accordion for chrome and legability

- themes/docker-2016/layouts/_default/single.html
- themes/docker-2016/layouts/partials/navbar-inner.html
- themes/docker-2016/static/documentation.css
1. Cleaned up left hand menu by fixing the arrow getting pushed off by long text.
- Before:
- After:
2. Removed the top-level link in the table of contents, stopped the links from falling off the right hand side of the page, and removed some unnecessary padding.
- Before:
- After:
> Various menu fixes

- data/advisories.toml
re-enables the advisory for component project "Docker Swarm" docs to help reduce confusion with "swarm mode" in Engine
Signed-off-by: Charles Smith <charles.smith@docker.com>
> re-enable advisory banner for Docker Swarm
