docker/docs-base

theme/mkdocs/css/docs.css

Moving over https://github.com/docker/docker/pull/9726

Adding in the mobile

---

README.md

Maybe an alternative could be `set it up in you repository`?

Fix sentence breaking word in README

---

config.toml

Adjusting suggested menu

---

config.toml

Adding in new contribute materieal

---

layouts/index.html
layouts/partials/buildinfo.html
layouts/partials/container-footer.html

Adding area for build information

---

content/test.md
content/test2.md
content/test3.md
layouts/_default/single.html
layouts/index.html
layouts/partials/buildinfo.html

Updating layouts to support BUILD_DATA work from mike in docs.docker.com

Hugo Updates

---

layouts/_default/single.html
layouts/index.html

Updating with fixes to remove extra heading

---

content/test.md
content/test2.md
content/test3.md
layouts/partials/navbar.html

Links were not working in the children. Fixed this

---

content/test2.md
layouts/partials/navbar.html

Menu depth wasn't quite working. This fixes it.

Fixing the menu depth

---

layouts/partials/container-footer.html
layouts/partials/navbar.html
static/css/custom.css

Navbar has active state and knows the current page.

---

config.toml

Updating config.toml to include BlackFriday options

---

config.toml

Hugo remove redundant release notes

---

layouts/partials/header.html
layouts/partials/mac-navbar.html
static/css/custom.css

Styled tut menu and fixed detecting active page not working.

---

layouts/partials/linux-navbar.html
layouts/partials/windows-navbar.html

Adding the navbars

---

layouts/partials/linux-navbar.html
layouts/partials/windows-navbar.html

Fixing active link

---

content/index.md

Fixing theimage

---

layouts/partials/footer.html

Fannette needs the tag code out of a div

Moving tag code out of div

---

layouts/partials/container-footer.html

Updating with information for Fannette

---

config.toml
content/release-notes.md

Moving from docs to here and updating for Monday

Update for june

---

config.toml

Renaming Docker Hub Enterprise

Updated for the release

---

config.toml

Adding logging driver to menu

---

config.toml

Updating for the cli breakout

---

config.toml

Adding menu for logging drivers.

---

config.toml

Hide logging that's next release

---

content/index.md

Fixing front page

---

layouts/partials/buildinfo.html
layouts/partials/container-footer.html
layouts/partials/footer.html

- removed unneeded partials
- reduced bottom footer
- BUILD_DATA

Fix #67 and BUILD_DATA

---

content/test.md
layouts/_default/single.html
static/css/custom.css

Old behavior which is menu doesn't move
Fixed toc like old school
Increase page width
Styling list

Adding TOC

---

layouts/_default/single.html
layouts/index.html
static/css/custom.css

Adjusting page width on Index too

Taking getting started into account

---

static/css/custom.css

Fixing the float on the div

---

content/test.md
static/css/custom.css

Updating with new css that blocks head levels below 3 from display.

Hide level 3 heads

---

layouts/partials/header.html

Adding hard link to the favicon

---

content/test.md
static/css/custom.css

Adding in the styling Seb did

---

config.toml

Updating with config per-mike

---

config.toml

Signed-off-by: Tristan Carel <tristan.carel@gmail.com>

Fix typo in TOC

---

config.toml

Moved the menu item into docker/docker

---

config.toml

Fixing old archive doc links

---

config.toml
content/test.md
layouts/shortcodes/thebaseurl.html

- Adding shortcode for creating relative urls
- Removing comment re logging that's handled in the repo
- Renaming older to archived

Adding baseurl support and tweaks to config

---

content/index.md
layouts/partials/header.html

Fixing the hub links

---

config.toml
content/release-notes.md

- 1.7 is in archive
- release notes update
- hrefs in release notes

Adding in 1.7 to archive

---

content/index.md
layouts/partials/header.html

Updating hub links

---

content/release-notes.md

Updating for compose

---

config.toml

Fixing menu

---

content/index.md
content/release-notes.md
layouts/partials/header.html

- Removing bad redirect
- Adding 1.8.1 to release notes
- Also making sure to generate meta description / keywords

- Meta-tags not generating

---

content/index.md
content/release-notes.md

While reading the docs, I spotted a few typos and missing spaces.
Signed-off-by: Lynda O'Leary <lyndaoleary29@gmail.com>

Changed typos and spacing errors

---

Dockerfile
Makefile
validate.sh

Add a validate.sh that will be called by jenkins

---

layouts/mario/single.html
layouts/partials/mario-navbar.html

Mario testing

---

content/release-notes.md

Update release notes for 1.83

---

LICENSE

Put the things in the license

---

Dockerfile

use new improved less verbose markdownlint

---

Dockerfile

update to markdownlink v0.9.2

---

Dockerfile

Use markdownlint v0.9.2

---

Makefile
config.toml
jenkins-validate.sh
validate.sh

Move the Jenkins job shell commands into a script

---

jenkins-validate.sh

Run the validate.sh script - the image CMD

---

validate.sh

Send fake junit.xml for markdownlint and hugo build

---

jenkins-validate.sh

Copy the junit.xml files out of the containerized test run

---

config.toml

This is a quick addition of the 1.8 to the archive menu.

Adding 1.8 archive

---

jenkins-validate.sh

Clear out old junit XML reports before we start the job

---

jenkins-validate.sh
validate.sh

More bashing

---

jenkins-validate.sh

add echo on to see where the jenkins job is falling over

---

jenkins-validate.sh

Allow for old branched docs/base that doesn't yet output the xml

---

jenkins-validate.sh

It seems I can't type spaces or double pipes

---

jenkins-validate.sh

Ignore validate.sh error code, as we're gettingback the XML instead

---

content/index.md

These moved to the /engine/ dir

---

config.toml

related to https://github.com/spf13/hugo/issues/1659
Hugo isn't obvious - the error you'll see if complaining that it can't find the layout file:
```
docker run --rm -it  -e AWS_S3_BUCKET -e NOCACHE --name docker-docs-tools -p 8000:8000 -e DOCKERHOST "docs-base:master" hugo server --port=8000 --baseUrl=localhost --bind=0.0.0.0 --config=./config.toml
INFO: 2015/12/02 Using config file: ./config.toml
INFO: 2015/12/02 syncing from /docs/themes/hugo-foundation/static to /docs/public/
INFO: 2015/12/02 syncing from /docs/static/ to /docs/public/
ERROR: 2015/12/02 loadData at 
ERROR: 2015/12/02 LinkResolver: No page found for "/compose/install.md" on page "security/trust/deploying_notary.md".
INFO: 2015/12/02 found taxonomies: …
```

Make Hugo output a warning when there are missing index.md files

---

layouts/docker-cloud/single.html
layouts/partials/cloud-navbar.html

Changes in support of the tutum

Updating for tutum

---

Dockerfile

, i have the stack trace i want, and it introduces a GH linking issue
@moxiegirl I'm hoping this will fix the `.md` linking issue you found - I'll need to dig into that later (and add more tests to hugo.

Stop using the debug build

---

jenkins-validate.sh

so I can then expose it on the jenkins job.

Copy the markdownlint summary file out of the container

---

layouts/linux/single.html
layouts/mac/single.html
layouts/windows/single.html

Fixing the docs for tutorials

---

layouts/404.html

try this to fix part of the 404 problem.

---

config.toml

Fixing config.toml

---

config.toml

Adding 1.10 to the archive list.  

Adding 1.10 archive to the list

---

Dockerfile
Makefile

Upgrade to Hugo 0.16-pre4

---

Dockerfile
Makefile

Reverts docker/docs-base#250
looks like there was a notable change - the Aliases resolution added some errors
I'll fix those first :(

Revert "Upgrade to Hugo 0.16-pre4"

---

layouts/partials/container-footer.html

Simplify the HTML output by removing the buildinfo

---

content/test/index.md
content/test/menu.md

make the example test menu draft, so it won't show in builds

---

layouts/partials/footer.html

@sanscontext @joaofnfernandes @londoncalling @sfsmithcha @patrickqnguyen

Reduce the scope of the GA Analytics

---

oss-projects/Dockerfile

GH's svn isn't reliable, moving to git

---

Dockerfile

We've fixed enough errors to make upgrading useful

---

Dockerfile

Alternate to #264

---

Dockerfile

Ignore more links

---

content/index.md

Fix some broken HTML in the index.md page

---

Dockerfile
themes/docker-2016/layouts/partials/footer.html
themes/docker-2016/layouts/partials/header.html

Use https where we can

---

config.toml

Sitemap, we need it!

---

data/advisories.toml

Update Swarm advisory to be stronger to redirect users to "swarm mode"
Signed-off-by: Charles Smith <charles.smith@docker.com>

make swarm advisory more forceful

---

content/thank-you-subscribing-docker-weekly.md

Basic copy of http://www.docker.com/thank-you-subscribing-docker-weekly

---

Dockerfile

make both markdownlint and linkcheck less chatty

---

Dockerfile

make error report more obvious

---

themes/docker-2016/static/documentation.css

Signed-off-by: fish <fisher@docker.com>
@SvenDowideit @sanscontext @jsouth

added padding for legibility via blockquote text

---

themes/docker-2016/static/assets/css/allcss.css
themes/docker-2016/static/assets/css/app2.css
themes/docker-2016/static/documentation.css

@SvenDowideit @jsouth @sanscontext

Updated header + sidenav/accordion 

---

Dockerfile

I'm hoping this will help with things like https://github.com/docker/docker/pull/24572

Skip http client errors, they cause false negatives

---

Makefile
oss-projects/Dockerfile

Build image used by checkers from the v1.12.0 docs source
